name: robotica
channels:
  - conda-forge
dependencies:
  - python=3.8.16
  - pybullet
  - pip
  - pip:
      - numpy==1.23.5
      - pandas==2.0.3
      - scipy==1.10.0
      - matplotlib==3.7.2
      - pyserial==3.5
      - pygame==2.5.0
      - websockets==11.0.3
      - opencv-contrib-python==4.8.0.76